### ISSUE TITLE
JS errors on Yosemite Safari 8.0.5 

### ISSUE THREAD

**Issue by lihan** [TopCloud/socketcluster-client#5]
Just run the sample app, and you'll see a few console errors.

![image](https://cloud.githubusercontent.com/assets/655051/7273507/bb3e9b86-e937-11e4-9f80-d8051712761d.png)

Complete console logs

[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	_sendObject (socketcluster.js, line 945)
	_emitRaw (socketcluster.js, line 969)
	_emitDirect (socketcluster.js, line 1018)
	_trySubscribe (socketcluster.js, line 1115)
	(anonymous function) (socketcluster.js, line 1263)
	_resubscribe (socketcluster.js, line 1265)
	_onSCOpen (socketcluster.js, line 582)
	onopen (socketcluster.js, line 543)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	_sendObject (socketcluster.js, line 945)
	sendObject (socketcluster.js, line 953)
	disconnect (socketcluster.js, line 560)
	unloadHandler (socketcluster.js, line 458)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	_sendObject (socketcluster.js, line 945)
	_emitRaw (socketcluster.js, line 969)
	_emitDirect (socketcluster.js, line 1018)
	_trySubscribe (socketcluster.js, line 1115)
	(anonymous function) (socketcluster.js, line 1263)
	_resubscribe (socketcluster.js, line 1265)
	_onSCOpen (socketcluster.js, line 582)
	onopen (socketcluster.js, line 543)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33, x2)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Error] ReferenceError: Can't find variable: callback
	_handleEventAckTimeout (socketcluster.js, line 996)
	(anonymous function) (socketcluster.js, line 1013)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	_sendObject (socketcluster.js, line 945)
	sendObject (socketcluster.js, line 953)
	disconnect (socketcluster.js, line 560)
	unloadHandler (socketcluster.js, line 458)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	_sendObject (socketcluster.js, line 945)
	_emitRaw (socketcluster.js, line 969)
	_emitDirect (socketcluster.js, line 1018)
	_trySubscribe (socketcluster.js, line 1115)
	(anonymous function) (socketcluster.js, line 1263)
	_resubscribe (socketcluster.js, line 1265)
	_onSCOpen (socketcluster.js, line 582)
	onopen (socketcluster.js, line 543)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33, x2)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33, x3)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Error] ReferenceError: Can't find variable: callback
	_handleEventAckTimeout (socketcluster.js, line 996)
	(anonymous function) (socketcluster.js, line 1013)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33, x2)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33, x2)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33, x2)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	send (socketcluster.js, line 949)
	_onSCMessage (socketcluster.js, line 732)
	onmessage (socketcluster.js, line 551)
[Log] RANDOM: 2 :) (127.0.0.1, line 33, x2)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33, x3)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33, x3)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33, x2)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33, x2)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	send (socketcluster.js, line 949)
	_onSCMessage (socketcluster.js, line 732)
	onmessage (socketcluster.js, line 551)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33, x2)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33, x2)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Error] Socket error - Error: Client pong timed out
	(anonymous function) (127.0.0.1, line 18)
	emit (socketcluster.js, line 1419)
	(anonymous function) (socketcluster.js, line 632)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	_sendObject (socketcluster.js, line 945)
	_emitRaw (socketcluster.js, line 969)
	_emitDirect (socketcluster.js, line 1018)
	_trySubscribe (socketcluster.js, line 1115)
	(anonymous function) (socketcluster.js, line 1263)
	_resubscribe (socketcluster.js, line 1265)
	_onSCOpen (socketcluster.js, line 582)
	onopen (socketcluster.js, line 543)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Error] ReferenceError: Can't find variable: callback
	_handleEventAckTimeout (socketcluster.js, line 996)
	(anonymous function) (socketcluster.js, line 1013)
[Log] RANDOM: 1 :D (127.0.0.1, line 33, x2)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33, x2)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	send (socketcluster.js, line 949)
	_onSCMessage (socketcluster.js, line 732)
	onmessage (socketcluster.js, line 551)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33, x2)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33, x2)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33, x2)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	send (socketcluster.js, line 949)
	_onSCMessage (socketcluster.js, line 732)
	onmessage (socketcluster.js, line 551)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Error] Socket error - Error: Client pong timed out
	(anonymous function) (127.0.0.1, line 18)
	emit (socketcluster.js, line 1419)
	(anonymous function) (socketcluster.js, line 632)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	_sendObject (socketcluster.js, line 945)
	_emitRaw (socketcluster.js, line 969)
	_emitDirect (socketcluster.js, line 1018)
	_trySubscribe (socketcluster.js, line 1115)
	(anonymous function) (socketcluster.js, line 1263)
	_resubscribe (socketcluster.js, line 1265)
	_onSCOpen (socketcluster.js, line 582)
	onopen (socketcluster.js, line 543)
[Log] RANDOM: 2 :) (127.0.0.1, line 33, x2)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33, x2)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Error] ReferenceError: Can't find variable: callback
	_handleEventAckTimeout (socketcluster.js, line 996)
	(anonymous function) (socketcluster.js, line 1013)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33, x4)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33, x2)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	send (socketcluster.js, line 949)
	_onSCMessage (socketcluster.js, line 732)
	onmessage (socketcluster.js, line 551)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33, x3)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33, x2)
[Log] RANDOM: 1 :D (127.0.0.1, line 33, x2)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33, x2)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33, x2)
[Log] RANDOM: 1 :D (127.0.0.1, line 33, x3)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	send (socketcluster.js, line 949)
	_onSCMessage (socketcluster.js, line 732)
	onmessage (socketcluster.js, line 551)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33, x3)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33)
[Error] Socket error - Error: Client pong timed out
	(anonymous function) (127.0.0.1, line 18)
	emit (socketcluster.js, line 1419)
	(anonymous function) (socketcluster.js, line 632)
[Error] TypeError: Type error
	send (socketcluster.js, line 940)
	_send (socketcluster.js, line 940)
	_sendObject (socketcluster.js, line 945)
	_emitRaw (socketcluster.js, line 969)
	_emitDirect (socketcluster.js, line 1018)
	_trySubscribe (socketcluster.js, line 1115)
	(anonymous function) (socketcluster.js, line 1263)
	_resubscribe (socketcluster.js, line 1265)
	_onSCOpen (socketcluster.js, line 582)
	onopen (socketcluster.js, line 543)
[Log] RANDOM: 4 ;) (127.0.0.1, line 33, x2)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 3 :3 (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33, x2)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Error] ReferenceError: Can't find variable: callback
	_handleEventAckTimeout (socketcluster.js, line 996)
	(anonymous function) (socketcluster.js, line 1013)
[Log] RANDOM: 2 :) (127.0.0.1, line 33)
[Log] RANDOM: 1 :D (127.0.0.1, line 33)
[Log] RANDOM: 0 ;p (127.0.0.1, line 33)

**Comment by jondubois** [comment]
I will have to check. Does sc2 work?

**Comment by jondubois** [comment]
This has been resolved. Incompatible client version was the cause.
